name: JSDoc

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate docs
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./source
          output_dir: ./docs
          template: minami
          recurse: true

      - name: Push docs
        run: |
          cd docs
          git add -A
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "Automated documentation"
          git push